COAL_ORE: 2
DEEPSLATE_COAL_ORE: 2
COPPER_ORE: 3
DEEPSLATE_COPPER_ORE: 3
DIAMOND_ORE: 10
DEEPSLATE_DIAMOND_ORE: 10
EMERALD_ORE: 8
DEEPSLATE_ELERALD_ORE: 8
GOLD_ORE: 3
NETHER_GOLD_ORE: 3
DEEPSLATE_GOLD_ORE: 3
IRON_ORE: 6
DEEPSLATE_IRON_ORE: 6
LAPIS_ORE: 5
DEEPSLATE_LAPIS_ORE: 5
REDSTONE_ORE: 5
DEEPSLATE_REDSTONE_ORE: 5
NETHER_QUARTZ_ORE: 7